name: Run Spoonacular Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code du repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Ajuste selon la version utilisée

      - name: Install dependencies
        run: pip install -r requirements.txt  # Installe les dépendances

      - name: Run script
        run: python script1.py && python script2.py  # Lance tes scripts

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Mise à jour des données"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
